language: python
os: linux

python:
  - 3.8
  
install:
  - pip install -r requirements.txt

before_script:
  - python ./greenCan/manage.py makemigrations
  - python ./greenCan/manage.py migrate

script:
  - python -m black . --check --line-length=99
  - python -m flake8 --exclude=migrations --max-line-length=99
  - python greenCan/manage.py collectstatic
  - cd greenCan && python -m coverage run --source=accounts,home,reuse,recycle,rewards,reduce,helper manage.py test --keepdb

after_success:
  - python -m coveralls
